name: Proto files generation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Protoc installation
      uses: arduino/setup-protoc@v3

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'
        cache-dependency-path: gen/go/go.sum
    - run: go env -w GO111MODULE=auto
    
    - name: Proto generation
      run: make
